spring:
  application:
    name: user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_SERVICE}:5432/${POSTGRES_DB_NAME}
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
#  cloud:
#    kubernetes:
#      discovery:
#        all-namespaces: true
