spring:
  application:
    name: user-srv
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_SERVICE}:5432/${POSTGRES_DB_NAME}
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true
    baseline-version: 0.0.1
#  cloud:
#    kubernetes:
#      discovery:
#        all-namespaces: true
logging:
  level:
    ru: debug
